<a href="https://colab.research.google.com/github/faizaan0619/MachineLearning/blob/main/Supervised/Logistic_Regression_customer_churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import KFold, cross_val_score

In [5]:
df = pd.read_csv('customer_churn_dataset-testing-master.csv')

In [6]:
df.sample(5)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
14771,14772,58,Male,19,22,0,28,Basic,Quarterly,831,8,0
26534,26535,53,Male,58,6,9,17,Basic,Quarterly,127,9,1
37575,37576,23,Female,25,17,8,22,Basic,Quarterly,785,25,1
35887,35888,61,Male,26,30,1,23,Basic,Monthly,337,20,0
12974,12975,19,Female,17,27,4,24,Standard,Annual,912,3,0

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
64369    False
64370    False
64371    False
64372    False
64373    False
Length: 64374, dtype: bool

In [8]:
df.shape

(64374, 12)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [10]:
df = pd.get_dummies(df, columns=["Gender", "Subscription Type", "Contract Length"], dtype=int)

In [11]:
X = df.drop(["Churn", "CustomerID"], axis=1)
y = df["Churn"]

In [12]:
X.head()

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Gender_Female,Gender_Male,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
0,22,25,14,4,27,598,9,1,0,1,0,0,0,1,0
1,41,28,28,7,13,584,20,1,0,0,0,1,0,1,0
2,47,27,10,2,29,757,21,0,1,0,1,0,1,0,0
3,35,9,12,5,17,232,18,0,1,0,1,0,0,0,1
4,53,58,24,9,2,533,18,1,0,0,0,1,1,0,0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
model = LogisticRegression(max_iter=1000)

In [16]:
param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "solver": ["liblinear", "lbfgs"]
}

In [17]:
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring="f1"
)

In [18]:
grid_search.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': [0.01, 0.1, 1, 10],
                         'solver': ['liblinear', 'lbfgs']},
             scoring='f1')

In [20]:
print(grid_search.best_params_)

{'C': 0.01, 'solver': 'liblinear'}

In [21]:
best_model = grid_search.best_estimator_

In [22]:
y_pred = best_model.predict(X_test_scaled)

In [23]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.8319223300970874
F1 Score: 0.8238071975248331
[[5652 1141]
 [1023 5059]]

In [24]:
accuracy_score(y_test, y_pred)

0.8319223300970874

In [25]:
f1_score(y_test,y_pred)

0.8238071975248331

In [26]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[5652, 1141],
       [1023, 5059]])