<a href="https://colab.research.google.com/github/faizaan0619/MachineLearning/blob/main/Supervised/SMS_Spam_Classifier_using_Multinomial_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/sms_spam_dataset_10k.csv')
df.head()

  label                                            message
0  spam  You have been chosen for a FREE gift. Reply YE...
1  spam  Congratulations! You have won $5,000. Claim yo...
2   ham            Thanks for helping me with the project.
3  spam  URGENT WINNER ALERT! Your prize of £1,000 is r...
4   ham  Your appointment is confirmed for Friday at to...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    10000 non-null  object
 1   message  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [ ]:
X = df['message']
y = df['label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.25, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
print(X_train_tfidf.shape)

(7500, 197)

In [ ]:
print(vectorizer.get_feature_names_out())

['000' '02079460000' '08001234567' '09012345678' '09123456789' '10' '15'
 '20' '30' '40' '50' '500' '70' '80' 'account' 'act' 'after' 'aisha'
 'alert' 'alex' 'am' 'an' 'and' 'apply' 'appointment' 'approved' 'are'
 'arrived' 'at' 'back' 'be' 'been' 'before' 'birthday' 'bonus' 'bring'
 'buy' 'by' 'call' 'can' 'cash' 'chosen' 'claim' 'class' 'click' 'collect'
 'come' 'confirmed' 'congratulations' 'contact' 'could' 'david' 'day'
 'delayed' 'dinner' 'discount' 'documents' 'don' 'downstairs' 'draw'
 'earn' 'email' 'emma' 'ends' 'every' 'exclusive' 'expires' 'extra' 'file'
 'final' 'for' 'forget' 'free' 'friday' 'from' 'get' 'gift' 'great'
 'happy' 'has' 'have' 'helping' 'here' 'hey' 'home' 'hope' 'immediately'
 'in' 'info' 'interest' 'is' 'it' 'john' 'know' 'late' 'let' 'limited'
 'little' 'll' 'loan' 'low' 'lucky' 'maya' 'me' 'meeting' 'midnight'
 'mike' 'milk' 'minutes' 'mobile' 'mom' 'monday' 'morning' 'near' 'next'
 'noon' 'notes' 'notice' 'now' 'number' 'of' 'off' 'offer' 'on' 'one'
 'opt' 'order' 'our' 'out' 'pick' 'please' 'pm' 'pre' 'prize' 'project'
 'promotion' 'purchase' 'qualify' 'quick' 'reach' 'ready' 'receive'
 'remind' 'reply' 'reschedule' 'result' 'reward' 'rich' 'ringtone'
 'running' 'ryan' 'safely' 'sam' 'sara' 'saturday' 'see' 'selected' 'send'
 'sent' 'smartphone' 'some' 'special' 'starts' 'station' 'still' 'stop'
 'subscription' 'team' 'thanks' 'the' 'there' 'thursday' 'time' 'to'
 'today' 'tomorrow' 'tonight' 'train' 'tuesday' 'up' 'urgent' 'us'
 'vacation' 've' 'waiting' 'way' 'we' 'wednesday' 'week' 'when' 'winner'
 'with' 'won' 'worth' 'yes' 'you' 'your']

In [ ]:
tfidf_df = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head()

,000,02079460000,08001234567,09012345678,09123456789,10,15,20,30,40,...,wednesday,week,when,winner,with,won,worth,yes,you,your
0,0.270278,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.344729,0.0,0.000000,0.0,0.0,0.000000,0.200588
1,0.000000,0.0,0.0,0.493169,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.318485,0.0,0.000000,0.0,0.0,0.166352,0.185317
2,0.224547,0.0,0.0,0.000000,0.441531,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.268444,0.0,0.0,0.000000,0.166649
3,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
4,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.155103,0.000000

In [ ]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_tfidf)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test, y_pred))

1.0

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      1245
        spam       1.00      1.00      1.00      1255

    accuracy                           1.00      2500
   macro avg       1.00      1.00      1.00      2500
weighted avg       1.00      1.00      1.00      2500

In [ ]:
new_message = ["Congratulations! You have won a free trip to Hawaii.",
               "Can we have a meeting.",
               "Claim your free prize now"
               ]
new_message_tfidf = vectorizer.transform(new_message)
prediction = model.predict(new_message_tfidf)
print(prediction)

['spam' 'ham' 'spam']

In [ ]:
prob = model.predict_proba(new_message_tfidf)
print(prob)

[[2.47159432e-03 9.97528406e-01]
 [9.99520945e-01 4.79054642e-04]
 [2.00504074e-04 9.99799496e-01]]

In [ ]:
new_message = ["Get 20% off on one8 shoes"]
new_message_tfidf = vectorizer.transform(new_message)
prediction = model.predict(new_message_tfidf)
print(prediction)

['spam']